### ISSUE TITLE
Landscape breaks layout

### ISSUE THREAD

**Issue by steven-spiel** [hawkinsjb1/responsive_util#1]
Great plugin! Thank you for developing it.

I'm seeing an issue across devices that when I change orientation, the view is constricted to the shortest side.

<img width="540" alt="Screen Shot 2021-02-16 at 10 08 36 AM" src="https://user-images.githubusercontent.com/77690617/108081460-fe337300-703e-11eb-888c-a54437e98aac.png">
<img width="1038" alt="Screen Shot 2021-02-16 at 10 08 38 AM" src="https://user-images.githubusercontent.com/77690617/108081464-fe337300-703e-11eb-9a40-fed159171757.png">

```
Scaffold(
  body: Column(
    mainAxisAlignment: MainAxisAlignment.spaceBetween,
    children: [
      Expanded(child: Container(color: Colors.red)),
      Expanded(child: Container(color: Colors.green)),
    ],
  ),
)
```

**Comment by hawkinsjb1** [comment]
So sorry about the delay, this is fixed in the most recent version!
